import streamlit as st
from streamlit_keplergl import keplergl_static
from keplergl import KeplerGl

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
import seaborn as sns
import altair as alt
#CWD = f'/content/drive/MyDrive/Sherem_streamlit/'
#input_path = f'{CWD}input/'
map_config = './map_config/'

map_config_in = {'version': 'v1',
 'config': {'visState': {'filters': [{'dataId': ['all_data'],
     'id': 'dqm3foztf',
     'name': ['INB_DATE_TIME'],
     'type': 'timeRange',
     'value': [1651360620000, 1651446040000],
     'enlarged': True,
     'plotType': 'histogram',
     'animationWindow': 'free',
     'yAxis': None,
     'speed': 0.75}],
   'layers': [{'id': 'ko3a0p9',
     'type': 'arc',
     'config': {'dataId': 'all_data',
      'label': 'Flights_in',
      'color': [218, 112, 191],
      'highlightColor': [252, 242, 26, 255],
      'columns': {'lat0': 'Lat_from',
       'lng0': 'Lon_from',
       'lat1': 'Lat_to',
       'lng1': 'Lon_to'},
      'isVisible': True,
      'visConfig': {'opacity': 0.8,
       'thickness': 3,
       'colorRange': {'name': 'Custom Palette',
        'type': 'custom',
        'category': 'Custom',
        'colors': ['#ff7f00',
         '#a6cee3',
         '#1f78b4',
         '#b2df8a',
         '#33a02c',
         '#fb9a99',
         '#e31a1c',
         '#B4CB8C',
         '#cab2d6',
         '#6a3d9a',
         '#ffff99',
         '#ADFF2F',
         '#00FF00',
         '#00FA9A',
         '#006400\t',
         '#66CDAA',
         '#FFE4B5',
         '#BDB76B',
         '#E6E6FA',
         '#D8BFD8',
         '#FF00FF',
         '#9370DB',
         '#8B008B',
         '#4B0082',
         '#000080',
         '#0000FF',
         '#1E90FF',
         '#B0E0E6\t',
         '#008080\t',
         '#556B2F',
         '#808000',
         '#9ACD32',
         '#2F4F4F',
         '#BC8F8F',
         '#A52A2A',
         '#BA55D3',
         '#2E8B57',
         '#FFD700',
         '#FFFF00',
         '#FFEFD5',
         '#00CED1',
         '#00CED1#2F4F4F',
         '#808080']},
       'sizeRange': [0, 10],
       'targetColor': None},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'colorField': {'name': 'Airline_Name',
       'type': 'string'},
      'colorScale': 'ordinal',
      'sizeField': None,
      'sizeScale': 'linear'}}],
   'interactionConfig': {'tooltip': {'fieldsToShow': {'all_data': [{'name': 'AircraftType',
        'format': None},
       {'name': 'REG', 'format': None},
       {'name': 'INB_FLIGHT', 'format': None},
       {'name': 'INB_DATE_TIME', 'format': None},
       {'name': 'TOWN_FROM', 'format': None},
       {'name': 'COUNTRY', 'format': None}]},
     'compareMode': False,
     'compareType': 'absolute',
     'enabled': True},
    'brush': {'size': 0.5, 'enabled': False},
    'geocoder': {'enabled': False},
    'coordinate': {'enabled': False}},
   'layerBlending': 'normal',
   'splitMaps': [],
   'animationConfig': {'currentTime': None, 'speed': 1}},
  'mapState': {'bearing': 0,
   'dragRotate': False,
   'latitude': 41.657649375490124,
   'longitude': 89.14569946102559,
   'pitch': 0,
   'zoom': 2.0767292986029195,
   'isSplit': False},
  'mapStyle': {'styleType': 'm5bk6dm',    #'ini2ac'
   'topLayerGroups': {},
   'visibleLayerGroups': {'label': True,
    'road': True,
    'building': True,
    'water': True,
    'land': True},
   'threeDBuildingColor': [194.6103322548211,
    191.81688250953655,
    185.2988331038727],
   'mapStyles': {'m5bk6dm': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'm5bk6dm',
     'label': 'Mapbox Streets',
     'url': 'mapbox://styles/mapbox/streets-v11'},
    'd65z8s4': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/navigation-day-v1/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'd65z8s4',
     'label': 'Mapbox Navigation Day',
     'url': 'mapbox://styles/mapbox/navigation-day-v1'},
    '9belde': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v11/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': '9belde',
     'label': 'Mapbox Satellite Streets',
     'url': 'mapbox://styles/mapbox/satellite-streets-v11'},
    'ini2ac': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/navigation-night-v1/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'ini2ac',
     'label': 'Mapbox Navigation Night',
     'url': 'mapbox://styles/mapbox/navigation-night-v1'}}}}}

map_config_in_dark = {'version': 'v1',
 'config': {'visState': {'filters': [{'dataId': ['all_data'],
     'id': 'dqm3foztf',
     'name': ['INB_DATE_TIME'],
     'type': 'timeRange',
     'value': [1651360620000, 1651446040000],
     'enlarged': True,
     'plotType': 'histogram',
     'animationWindow': 'free',
     'yAxis': None,
     'speed': 0.75}],
   'layers': [{'id': 'ko3a0p9',
     'type': 'arc',
     'config': {'dataId': 'all_data',
      'label': 'Flights_in',
      'color': [218, 112, 191],
      'highlightColor': [252, 242, 26, 255],
      'columns': {'lat0': 'Lat_from',
       'lng0': 'Lon_from',
       'lat1': 'Lat_to',
       'lng1': 'Lon_to'},
      'isVisible': True,
      'visConfig': {'opacity': 0.8,
       'thickness': 3,
       'colorRange': {'name': 'Custom Palette',
        'type': 'custom',
        'category': 'Custom',
        'colors': ['#ff7f00',
         '#a6cee3',
         '#1f78b4',
         '#b2df8a',
         '#33a02c',
         '#fb9a99',
         '#e31a1c',
         '#B4CB8C',
         '#cab2d6',
         '#6a3d9a',
         '#ffff99',
         '#ADFF2F',
         '#00FF00',
         '#00FA9A',
         '#006400\t',
         '#66CDAA',
         '#FFE4B5',
         '#BDB76B',
         '#E6E6FA',
         '#D8BFD8',
         '#FF00FF',
         '#9370DB',
         '#8B008B',
         '#4B0082',
         '#000080',
         '#0000FF',
         '#1E90FF',
         '#B0E0E6\t',
         '#008080\t',
         '#556B2F',
         '#808000',
         '#9ACD32',
         '#2F4F4F',
         '#BC8F8F',
         '#A52A2A',
         '#BA55D3',
         '#2E8B57',
         '#FFD700',
         '#FFFF00',
         '#FFEFD5',
         '#00CED1',
         '#00CED1#2F4F4F',
         '#808080']},
       'sizeRange': [0, 10],
       'targetColor': None},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'colorField': {'name': 'Airline_Name',
       'type': 'string'},
      'colorScale': 'ordinal',
      'sizeField': None,
      'sizeScale': 'linear'}}],
   'interactionConfig': {'tooltip': {'fieldsToShow': {'all_data': [{'name': 'AircraftType',
        'format': None},
       {'name': 'REG', 'format': None},
       {'name': 'INB_FLIGHT', 'format': None},
       {'name': 'INB_DATE_TIME', 'format': None},
       {'name': 'TOWN_FROM', 'format': None},
       {'name': 'COUNTRY', 'format': None}]},
     'compareMode': False,
     'compareType': 'absolute',
     'enabled': True},
    'brush': {'size': 0.5, 'enabled': False},
    'geocoder': {'enabled': False},
    'coordinate': {'enabled': False}},
   'layerBlending': 'normal',
   'splitMaps': [],
   'animationConfig': {'currentTime': None, 'speed': 1}},
  'mapState': {'bearing': 0,
   'dragRotate': False,
   'latitude': 41.657649375490124,
   'longitude': 89.14569946102559,
   'pitch': 0,
   'zoom': 2.0767292986029195,
   'isSplit': False},
  'mapStyle': {'styleType': 'ini2ac',   
   'topLayerGroups': {},
   'visibleLayerGroups': {'label': True,
    'road': True,
    'building': True,
    'water': True,
    'land': True},
   'threeDBuildingColor': [194.6103322548211,
    191.81688250953655,
    185.2988331038727],
   'mapStyles': {'m5bk6dm': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'm5bk6dm',
     'label': 'Mapbox Streets',
     'url': 'mapbox://styles/mapbox/streets-v11'},
    'd65z8s4': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/navigation-day-v1/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'd65z8s4',
     'label': 'Mapbox Navigation Day',
     'url': 'mapbox://styles/mapbox/navigation-day-v1'},
    '9belde': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v11/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': '9belde',
     'label': 'Mapbox Satellite Streets',
     'url': 'mapbox://styles/mapbox/satellite-streets-v11'},
    'ini2ac': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/navigation-night-v1/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'ini2ac',
     'label': 'Mapbox Navigation Night',
     'url': 'mapbox://styles/mapbox/navigation-night-v1'}}}}}

map_config_in_dark_noLegend = {'version': 'v1',
 'config': {'visState': {'filters': [{'dataId': ['all_data'],
     'id': 'dqm3foztf',
     'name': ['INB_DATE_TIME'],
     'type': 'timeRange',
     'value': [1651360620000, 1651446040000],
     'enlarged': False,
     'plotType': 'histogram',
     'animationWindow': 'free',
     'yAxis': None,
     'speed': 0.75}],
   'layers': [{'id': 'ko3a0p9',
     'type': 'arc',
     'config': {'dataId': 'all_data',
      'label': 'Flights_in',
      'color': [218, 112, 191],
      'highlightColor': [252, 242, 26, 255],
      'columns': {'lat0': 'Lat_from',
       'lng0': 'Lon_from',
       'lat1': 'Lat_to',
       'lng1': 'Lon_to'},
      'isVisible': True,
      'visConfig': {'opacity': 0.8,
       'thickness': 3,
       'colorRange': {'name': 'Custom Palette',
        'type': 'custom',
        'category': 'Custom',
        'colors': ['#ff7f00',
         '#a6cee3',
         '#1f78b4',
         '#b2df8a',
         '#33a02c',
         '#fb9a99',
         '#e31a1c',
         '#B4CB8C',
         '#cab2d6',
         '#6a3d9a',
         '#ffff99',
         '#ADFF2F',
         '#00FF00',
         '#00FA9A',
         '#006400\t',
         '#66CDAA',
         '#FFE4B5',
         '#BDB76B',
         '#E6E6FA',
         '#D8BFD8',
         '#FF00FF',
         '#9370DB',
         '#8B008B',
         '#4B0082',
         '#000080',
         '#0000FF',
         '#1E90FF',
         '#B0E0E6\t',
         '#008080\t',
         '#556B2F',
         '#808000',
         '#9ACD32',
         '#2F4F4F',
         '#BC8F8F',
         '#A52A2A',
         '#BA55D3',
         '#2E8B57',
         '#FFD700',
         '#FFFF00',
         '#FFEFD5',
         '#00CED1',
         '#00CED1#2F4F4F',
         '#808080']},
       'sizeRange': [0, 10],
       'targetColor': None},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'colorField': {'name': 'Airline_Name',
       'type': 'string'},
      'colorScale': 'ordinal',
      'sizeField': None,
      'sizeScale': 'linear'}}],
   'interactionConfig': {'tooltip': {'fieldsToShow': {'all_data': [{'name': 'AircraftType',
        'format': None},
       {'name': 'REG', 'format': None},
       {'name': 'INB_FLIGHT', 'format': None},
       {'name': 'INB_DATE_TIME', 'format': None},
       {'name': 'TOWN_FROM', 'format': None},
       {'name': 'COUNTRY', 'format': None}]},
     'compareMode': False,
     'compareType': 'absolute',
     'enabled': True},
    'brush': {'size': 0.5, 'enabled': False},
    'geocoder': {'enabled': False},
    'coordinate': {'enabled': False}},
   'layerBlending': 'normal',
   'splitMaps': [],
   'animationConfig': {'currentTime': None, 'speed': 1}},
  'mapState': {'bearing': 0,
   'dragRotate': False,
   'latitude': 41.657649375490124,
   'longitude': 89.14569946102559,
   'pitch': 0,
   'zoom': 2.0767292986029195,
   'isSplit': False},
  'mapStyle': {'styleType': 'ini2ac',
   'topLayerGroups': {},
   'visibleLayerGroups': {'label': True,
    'road': True,
    'building': True,
    'water': True,
    'land': True},
   'threeDBuildingColor': [194.6103322548211,
    191.81688250953655,
    185.2988331038727],
   'mapStyles': {'m5bk6dm': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'm5bk6dm',
     'label': 'Mapbox Streets',
     'url': 'mapbox://styles/mapbox/streets-v11'},
    'd65z8s4': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/navigation-day-v1/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'd65z8s4',
     'label': 'Mapbox Navigation Day',
     'url': 'mapbox://styles/mapbox/navigation-day-v1'},
    '9belde': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v11/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': '9belde',
     'label': 'Mapbox Satellite Streets',
     'url': 'mapbox://styles/mapbox/satellite-streets-v11'},
    'ini2ac': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/navigation-night-v1/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'ini2ac',
     'label': 'Mapbox Navigation Night',
     'url': 'mapbox://styles/mapbox/navigation-night-v1'}}}}}

map_config_in_noLegend = {'version': 'v1',
'config': {'visState': {'filters': [{'dataId': ['all_data'],
     'id': 'dqm3foztf',
     'name': ['INB_DATE_TIME'],
     'type': 'timeRange',
     'value': [1651360620000, 1651446040000],
     'enlarged': False,
     'plotType': 'histogram',
     'animationWindow': 'free',
     'yAxis': None,
     'speed': 0.75}],
   'layers': [{'id': 'ko3a0p9',
     'type': 'arc',
     'config': {'dataId': 'all_data',
      'label': 'Flights_in',
      'color': [218, 112, 191],
      'highlightColor': [252, 242, 26, 255],
      'columns': {'lat0': 'Lat_from',
       'lng0': 'Lon_from',
       'lat1': 'Lat_to',
       'lng1': 'Lon_to'},
      'isVisible': True,
      'visConfig': {'opacity': 0.8,
       'thickness': 3,
       'colorRange': {'name': 'Custom Palette',
        'type': 'custom',
        'category': 'Custom',
        'colors': ['#ff7f00',
         '#a6cee3',
         '#1f78b4',
         '#b2df8a',
         '#33a02c',
         '#fb9a99',
         '#e31a1c',
         '#B4CB8C',
         '#cab2d6',
         '#6a3d9a',
         '#ffff99',
         '#ADFF2F',
         '#00FF00',
         '#00FA9A',
         '#006400\t',
         '#66CDAA',
         '#FFE4B5',
         '#BDB76B',
         '#E6E6FA',
         '#D8BFD8',
         '#FF00FF',
         '#9370DB',
         '#8B008B',
         '#4B0082',
         '#000080',
         '#0000FF',
         '#1E90FF',
         '#B0E0E6\t',
         '#008080\t',
         '#556B2F',
         '#808000',
         '#9ACD32',
         '#2F4F4F',
         '#BC8F8F',
         '#A52A2A',
         '#BA55D3',
         '#2E8B57',
         '#FFD700',
         '#FFFF00',
         '#FFEFD5',
         '#00CED1',
         '#00CED1#2F4F4F',
         '#808080']},
       'sizeRange': [0, 10],
       'targetColor': None},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'colorField': {'name': 'Airline_Name',
       'type': 'string'},
      'colorScale': 'ordinal',
      'sizeField': None,
      'sizeScale': 'linear'}}],
   'interactionConfig': {'tooltip': {'fieldsToShow': {'all_data': [{'name': 'AircraftType',
        'format': None},
       {'name': 'REG', 'format': None},
       {'name': 'INB_FLIGHT', 'format': None},
       {'name': 'INB_DATE_TIME', 'format': None},
       {'name': 'TOWN_FROM', 'format': None},
       {'name': 'COUNTRY', 'format': None}]},
     'compareMode': False,
     'compareType': 'absolute',
     'enabled': True},
    'brush': {'size': 0.5, 'enabled': False},
    'geocoder': {'enabled': False},
    'coordinate': {'enabled': False}},
   'layerBlending': 'normal',
   'splitMaps': [],
   'animationConfig': {'currentTime': None, 'speed': 1}},
  'mapState': {'bearing': 0,
   'dragRotate': False,
   'latitude': 41.657649375490124,
   'longitude': 89.14569946102559,
   'pitch': 0,
   'zoom': 2.0767292986029195,
   'isSplit': False},
  'mapStyle': {'styleType': 'm5bk6dm',
   'topLayerGroups': {},
   'visibleLayerGroups': {'label': True,
    'road': True,
    'building': True,
    'water': True,
    'land': True},
   'threeDBuildingColor': [194.6103322548211,
    191.81688250953655,
    185.2988331038727],
   'mapStyles': {'m5bk6dm': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'm5bk6dm',
     'label': 'Mapbox Streets',
     'url': 'mapbox://styles/mapbox/streets-v11'},
    'd65z8s4': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/navigation-day-v1/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'd65z8s4',
     'label': 'Mapbox Navigation Day',
     'url': 'mapbox://styles/mapbox/navigation-day-v1'},
    '9belde': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v11/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': '9belde',
     'label': 'Mapbox Satellite Streets',
     'url': 'mapbox://styles/mapbox/satellite-streets-v11'},
    'ini2ac': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/navigation-night-v1/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'ini2ac',
     'label': 'Mapbox Navigation Night',
     'url': 'mapbox://styles/mapbox/navigation-night-v1'}}}}}

map_config_out = {'version': 'v1',
 'config': {'visState': {'filters': [{'dataId': ['all_data'],
     'id': 'dqm3foztf',
     'name': ['OUT_DATE_TIME'],
     'type': 'timeRange',
     'value': [1651367220000, 1651446040000],
     'enlarged': True,
     'plotType': 'histogram',
     'animationWindow': 'free',
     'yAxis': None,
     'speed': 0.2}],
   'layers': [{'id': 'ko3a0p9',
     'type': 'arc',
     'config': {'dataId': 'all_data',
      'label': 'Flights_out',
      'color': [218, 112, 191],
      'highlightColor': [252, 242, 26, 255],
      'columns': {'lat0': 'Lat_from',
       'lng0': 'Lon_from',
       'lat1': 'Lat_to',
       'lng1': 'Lon_to'},
      'isVisible': True,
      'visConfig': {'opacity': 0.8,
       'thickness': 3,
       'colorRange': {'name': 'Custom Palette',
        'type': 'custom',
        'category': 'Custom',
        'colors': ['#ff7f00',
         '#a6cee3',
         '#1f78b4',
         '#b2df8a',
         '#33a02c',
         '#fb9a99',
         '#e31a1c',
         '#B4CB8C',
         '#cab2d6',
         '#6a3d9a',
         '#ffff99',
         '#ADFF2F',
         '#00FF00',
         '#00FA9A',
         '#006400\t',
         '#66CDAA',
         '#FFE4B5',
         '#BDB76B',
         '#E6E6FA',
         '#D8BFD8',
         '#FF00FF',
         '#9370DB',
         '#8B008B',
         '#4B0082',
         '#000080',
         '#0000FF',
         '#1E90FF',
         '#B0E0E6\t',
         '#008080\t',
         '#556B2F',
         '#808000',
         '#9ACD32',
         '#2F4F4F',
         '#BC8F8F',
         '#A52A2A',
         '#BA55D3',
         '#2E8B57',
         '#FFD700',
         '#FFFF00',
         '#FFEFD5',
         '#00CED1',
         '#00CED1#2F4F4F',
         '#808080']},
       'sizeRange': [0, 10],
       'targetColor': None},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'colorField': {'name': 'Airline_Name',
       'type': 'string'},
      'colorScale': 'ordinal',
      'sizeField': None,
      'sizeScale': 'linear'}}],
   'interactionConfig': {'tooltip': {'fieldsToShow': {'all_data': [{'name': 'AircraftType',
        'format': None},
       {'name': 'REG', 'format': None},
       {'name': 'OUT_FLIGHT', 'format': None},
       {'name': 'OUT_DATE_TIME', 'format': None},
       {'name': 'TOWN_TO', 'format': None},
       {'name': 'COUNTRY', 'format': None}]},
     'compareMode': False,
     'compareType': 'absolute',
     'enabled': True},
    'brush': {'size': 0.5, 'enabled': False},
    'geocoder': {'enabled': False},
    'coordinate': {'enabled': False}},
   'layerBlending': 'normal',
   'splitMaps': [],
   'animationConfig': {'currentTime': None, 'speed': 1}},
  'mapState': {'bearing': 0,
   'dragRotate': False,
   'latitude': 41.657649375490124,
   'longitude': 89.14569946102559,
   'pitch': 0,
   'zoom': 2.0767292986029195,
   'isSplit': False},
  'mapStyle': {'styleType': 'm5bk6dm',
   'topLayerGroups': {},
   'visibleLayerGroups': {'label': True,
    'road': True,
    'building': True,
    'water': True,
    'land': True},
   'threeDBuildingColor': [194.6103322548211,
    191.81688250953655,
    185.2988331038727],
   'mapStyles': {'m5bk6dm': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'm5bk6dm',
     'label': 'Mapbox Streets',
     'url': 'mapbox://styles/mapbox/streets-v11'},
    'd65z8s4': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/navigation-day-v1/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'd65z8s4',
     'label': 'Mapbox Navigation Day',
     'url': 'mapbox://styles/mapbox/navigation-day-v1'},
    '9belde': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v11/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': '9belde',
     'label': 'Mapbox Satellite Streets',
     'url': 'mapbox://styles/mapbox/satellite-streets-v11'},
    'ini2ac': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/navigation-night-v1/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'ini2ac',
     'label': 'Mapbox Navigation Night',
     'url': 'mapbox://styles/mapbox/navigation-night-v1'}}}}}

map_config_out_dark = {'version': 'v1',
 'config': {'visState': {'filters': [{'dataId': ['all_data'],
     'id': 'dqm3foztf',
     'name': ['OUT_DATE_TIME'],
     'type': 'timeRange',
     'value': [1651367220000, 1651446040000],
     'enlarged': True,
     'plotType': 'histogram',
     'animationWindow': 'free',
     'yAxis': None,
     'speed': 0.2}],
   'layers': [{'id': 'ko3a0p9',
     'type': 'arc',
     'config': {'dataId': 'all_data',
      'label': 'Flights_out',
      'color': [218, 112, 191],
      'highlightColor': [252, 242, 26, 255],
      'columns': {'lat0': 'Lat_from',
       'lng0': 'Lon_from',
       'lat1': 'Lat_to',
       'lng1': 'Lon_to'},
      'isVisible': True,
      'visConfig': {'opacity': 0.8,
       'thickness': 3,
       'colorRange': {'name': 'Custom Palette',
        'type': 'custom',
        'category': 'Custom',
        'colors': ['#ff7f00',
         '#a6cee3',
         '#1f78b4',
         '#b2df8a',
         '#33a02c',
         '#fb9a99',
         '#e31a1c',
         '#B4CB8C',
         '#cab2d6',
         '#6a3d9a',
         '#ffff99',
         '#ADFF2F',
         '#00FF00',
         '#00FA9A',
         '#006400\t',
         '#66CDAA',
         '#FFE4B5',
         '#BDB76B',
         '#E6E6FA',
         '#D8BFD8',
         '#FF00FF',
         '#9370DB',
         '#8B008B',
         '#4B0082',
         '#000080',
         '#0000FF',
         '#1E90FF',
         '#B0E0E6\t',
         '#008080\t',
         '#556B2F',
         '#808000',
         '#9ACD32',
         '#2F4F4F',
         '#BC8F8F',
         '#A52A2A',
         '#BA55D3',
         '#2E8B57',
         '#FFD700',
         '#FFFF00',
         '#FFEFD5',
         '#00CED1',
         '#00CED1#2F4F4F',
         '#808080']},
       'sizeRange': [0, 10],
       'targetColor': None},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'colorField': {'name': 'Airline_Name',
       'type': 'string'},
      'colorScale': 'ordinal',
      'sizeField': None,
      'sizeScale': 'linear'}}],
   'interactionConfig': {'tooltip': {'fieldsToShow': {'all_data': [{'name': 'AircraftType',
        'format': None},
       {'name': 'REG', 'format': None},
       {'name': 'OUT_FLIGHT', 'format': None},
       {'name': 'OUT_DATE_TIME', 'format': None},
       {'name': 'TOWN_TO', 'format': None},
       {'name': 'COUNTRY', 'format': None}]},
     'compareMode': False,
     'compareType': 'absolute',
     'enabled': True},
    'brush': {'size': 0.5, 'enabled': False},
    'geocoder': {'enabled': False},
    'coordinate': {'enabled': False}},
   'layerBlending': 'normal',
   'splitMaps': [],
   'animationConfig': {'currentTime': None, 'speed': 1}},
  'mapState': {'bearing': 0,
   'dragRotate': False,
   'latitude': 41.657649375490124,
   'longitude': 89.14569946102559,
   'pitch': 0,
   'zoom': 2.0767292986029195,
   'isSplit': False},
  'mapStyle': {'styleType': 'ini2ac',
   'topLayerGroups': {},
   'visibleLayerGroups': {'label': True,
    'road': True,
    'building': True,
    'water': True,
    'land': True},
   'threeDBuildingColor': [194.6103322548211,
    191.81688250953655,
    185.2988331038727],
   'mapStyles': {'m5bk6dm': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'm5bk6dm',
     'label': 'Mapbox Streets',
     'url': 'mapbox://styles/mapbox/streets-v11'},
    'd65z8s4': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/navigation-day-v1/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'd65z8s4',
     'label': 'Mapbox Navigation Day',
     'url': 'mapbox://styles/mapbox/navigation-day-v1'},
    '9belde': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v11/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': '9belde',
     'label': 'Mapbox Satellite Streets',
     'url': 'mapbox://styles/mapbox/satellite-streets-v11'},
    'ini2ac': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/navigation-night-v1/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'ini2ac',
     'label': 'Mapbox Navigation Night',
     'url': 'mapbox://styles/mapbox/navigation-night-v1'}}}}}

map_config_out_dark_noLegend = {'version': 'v1',
 'config': {'visState': {'filters': [{'dataId': ['all_data'],
     'id': 'dqm3foztf',
     'name': ['OUT_DATE_TIME'],
     'type': 'timeRange',
     'value': [1651367220000, 1651446040000],
     'enlarged': False,
     'plotType': 'histogram',
     'animationWindow': 'free',
     'yAxis': None,
     'speed': 0.2}],
   'layers': [{'id': 'ko3a0p9',
     'type': 'arc',
     'config': {'dataId': 'all_data',
      'label': 'Flights_out',
      'color': [218, 112, 191],
      'highlightColor': [252, 242, 26, 255],
      'columns': {'lat0': 'Lat_from',
       'lng0': 'Lon_from',
       'lat1': 'Lat_to',
       'lng1': 'Lon_to'},
      'isVisible': True,
      'visConfig': {'opacity': 0.8,
       'thickness': 3,
       'colorRange': {'name': 'Custom Palette',
        'type': 'custom',
        'category': 'Custom',
        'colors': ['#ff7f00',
         '#a6cee3',
         '#1f78b4',
         '#b2df8a',
         '#33a02c',
         '#fb9a99',
         '#e31a1c',
         '#B4CB8C',
         '#cab2d6',
         '#6a3d9a',
         '#ffff99',
         '#ADFF2F',
         '#00FF00',
         '#00FA9A',
         '#006400\t',
         '#66CDAA',
         '#FFE4B5',
         '#BDB76B',
         '#E6E6FA',
         '#D8BFD8',
         '#FF00FF',
         '#9370DB',
         '#8B008B',
         '#4B0082',
         '#000080',
         '#0000FF',
         '#1E90FF',
         '#B0E0E6\t',
         '#008080\t',
         '#556B2F',
         '#808000',
         '#9ACD32',
         '#2F4F4F',
         '#BC8F8F',
         '#A52A2A',
         '#BA55D3',
         '#2E8B57',
         '#FFD700',
         '#FFFF00',
         '#FFEFD5',
         '#00CED1',
         '#00CED1#2F4F4F',
         '#808080']},
       'sizeRange': [0, 10],
       'targetColor': None},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'colorField': {'name': 'Airline_Name',
       'type': 'string'},
      'colorScale': 'ordinal',
      'sizeField': None,
      'sizeScale': 'linear'}}],
   'interactionConfig': {'tooltip': {'fieldsToShow': {'all_data': [{'name': 'AircraftType',
        'format': None},
       {'name': 'REG', 'format': None},
       {'name': 'OUT_FLIGHT', 'format': None},
       {'name': 'OUT_DATE_TIME', 'format': None},
       {'name': 'TOWN_TO', 'format': None},
       {'name': 'COUNTRY', 'format': None}]},
     'compareMode': False,
     'compareType': 'absolute',
     'enabled': True},
    'brush': {'size': 0.5, 'enabled': False},
    'geocoder': {'enabled': False},
    'coordinate': {'enabled': False}},
   'layerBlending': 'normal',
   'splitMaps': [],
   'animationConfig': {'currentTime': None, 'speed': 1}},
  'mapState': {'bearing': 0,
   'dragRotate': False,
   'latitude': 41.657649375490124,
   'longitude': 89.14569946102559,
   'pitch': 0,
   'zoom': 2.0767292986029195,
   'isSplit': False},
  'mapStyle': {'styleType': 'ini2ac',
   'topLayerGroups': {},
   'visibleLayerGroups': {'label': True,
    'road': True,
    'building': True,
    'water': True,
    'land': True},
   'threeDBuildingColor': [194.6103322548211,
    191.81688250953655,
    185.2988331038727],
   'mapStyles': {'m5bk6dm': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'm5bk6dm',
     'label': 'Mapbox Streets',
     'url': 'mapbox://styles/mapbox/streets-v11'},
    'd65z8s4': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/navigation-day-v1/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'd65z8s4',
     'label': 'Mapbox Navigation Day',
     'url': 'mapbox://styles/mapbox/navigation-day-v1'},
    '9belde': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v11/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': '9belde',
     'label': 'Mapbox Satellite Streets',
     'url': 'mapbox://styles/mapbox/satellite-streets-v11'},
    'ini2ac': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/navigation-night-v1/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'ini2ac',
     'label': 'Mapbox Navigation Night',
     'url': 'mapbox://styles/mapbox/navigation-night-v1'}}}}}

map_config_out_noLegend = {'version': 'v1',
 'config': {'visState': {'filters': [{'dataId': ['all_data'],
     'id': 'dqm3foztf',
     'name': ['OUT_DATE_TIME'],
     'type': 'timeRange',
     'value': [1651367220000, 1651446040000],
     'enlarged': False,
     'plotType': 'histogram',
     'animationWindow': 'free',
     'yAxis': None,
     'speed': 0.2}],
   'layers': [{'id': 'ko3a0p9',
     'type': 'arc',
     'config': {'dataId': 'all_data',
      'label': 'Flights_out',
      'color': [218, 112, 191],
      'highlightColor': [252, 242, 26, 255],
      'columns': {'lat0': 'Lat_from',
       'lng0': 'Lon_from',
       'lat1': 'Lat_to',
       'lng1': 'Lon_to'},
      'isVisible': True,
      'visConfig': {'opacity': 0.8,
       'thickness': 3,
       'colorRange': {'name': 'Custom Palette',
        'type': 'custom',
        'category': 'Custom',
        'colors': ['#ff7f00',
         '#a6cee3',
         '#1f78b4',
         '#b2df8a',
         '#33a02c',
         '#fb9a99',
         '#e31a1c',
         '#B4CB8C',
         '#cab2d6',
         '#6a3d9a',
         '#ffff99',
         '#ADFF2F',
         '#00FF00',
         '#00FA9A',
         '#006400\t',
         '#66CDAA',
         '#FFE4B5',
         '#BDB76B',
         '#E6E6FA',
         '#D8BFD8',
         '#FF00FF',
         '#9370DB',
         '#8B008B',
         '#4B0082',
         '#000080',
         '#0000FF',
         '#1E90FF',
         '#B0E0E6\t',
         '#008080\t',
         '#556B2F',
         '#808000',
         '#9ACD32',
         '#2F4F4F',
         '#BC8F8F',
         '#A52A2A',
         '#BA55D3',
         '#2E8B57',
         '#FFD700',
         '#FFFF00',
         '#FFEFD5',
         '#00CED1',
         '#00CED1#2F4F4F',
         '#808080']},
       'sizeRange': [0, 10],
       'targetColor': None},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'colorField': {'name': 'Airline_Name',
       'type': 'string'},
      'colorScale': 'ordinal',
      'sizeField': None,
      'sizeScale': 'linear'}}],
   'interactionConfig': {'tooltip': {'fieldsToShow': {'all_data': [{'name': 'AircraftType',
        'format': None},
       {'name': 'REG', 'format': None},
       {'name': 'OUT_FLIGHT', 'format': None},
       {'name': 'OUT_DATE_TIME', 'format': None},
       {'name': 'TOWN_TO', 'format': None},
       {'name': 'COUNTRY', 'format': None}]},
     'compareMode': False,
     'compareType': 'absolute',
     'enabled': True},
    'brush': {'size': 0.5, 'enabled': False},
    'geocoder': {'enabled': False},
    'coordinate': {'enabled': False}},
   'layerBlending': 'normal',
   'splitMaps': [],
   'animationConfig': {'currentTime': None, 'speed': 1}},
  'mapState': {'bearing': 0,
   'dragRotate': False,
   'latitude': 41.657649375490124,
   'longitude': 89.14569946102559,
   'pitch': 0,
   'zoom': 2.0767292986029195,
   'isSplit': False},
  'mapStyle': {'styleType': 'm5bk6dm',
   'topLayerGroups': {},
   'visibleLayerGroups': {'label': True,
    'road': True,
    'building': True,
    'water': True,
    'land': True},
   'threeDBuildingColor': [194.6103322548211,
    191.81688250953655,
    185.2988331038727],
   'mapStyles': {'m5bk6dm': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'm5bk6dm',
     'label': 'Mapbox Streets',
     'url': 'mapbox://styles/mapbox/streets-v11'},
    'd65z8s4': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/navigation-day-v1/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'd65z8s4',
     'label': 'Mapbox Navigation Day',
     'url': 'mapbox://styles/mapbox/navigation-day-v1'},
    '9belde': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v11/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': '9belde',
     'label': 'Mapbox Satellite Streets',
     'url': 'mapbox://styles/mapbox/satellite-streets-v11'},
    'ini2ac': {'accessToken': None,
     'custom': True,
     'icon': 'https://api.mapbox.com/styles/v1/mapbox/navigation-night-v1/static/-122.3391,37.7922,9,0,0/400x300?access_token=pk.eyJ1IjoidWNmLW1hcGJveCIsImEiOiJja3RpeXhkaXcxNzJtMnZxbmtkcnJuM3BkIn0.kGmGlkbuWaCBf7_RrZXULg&logo=false&attribution=false',
     'id': 'ini2ac',
     'label': 'Mapbox Navigation Night',
     'url': 'mapbox://styles/mapbox/navigation-night-v1'}}}}}

# Загрузить данные c прилетающими и улетающими рейсами
flights_in_coords = pd.read_csv('./input/flights_in_coords.csv')
flights_out_coords = pd.read_csv('./input/flights_out_coords.csv')

import streamlit as st

st.set_page_config(page_title='Forecasting the Revenue of Sheremetievo Airport Retail Outlets',
page_icon='https://alllogos.ru/images/logotip-sheremetevo.png', layout="wide")
#st.sidebar.image('https://pro-tile.ru/upload/resize_cache/iblock/95a/0_80_2/95ad2da1d04ff10c34faa68faa5aebe8.png', width=300)


# Sidebar Configuration
#add_logo("https://a-plex.ru/images/cms/thumbs/a4ffe087c89cb1feaf56d5f8a966f9bebe6ae94b/sheremetievologo_auto_141_png__85.png")

#st.sidebar.markdown('# Predicting Revenues of Sheremetievo Airport Retail Points')

st.sidebar.markdown('''<h2 style="text-align: left;"><img src="https://alllogos.ru/images/logotip-sheremetevo.png" width="25"/>
Sheremetievo Airport. Forecasting the Revenue of Retail Outlets</h2>''',
unsafe_allow_html=True)

st.sidebar.markdown('Sheremetievo is the second largest airport in Europe in terms of passenger traffic per year.')
st.sidebar.markdown('This App is designed to display revenue forecasts of retail outlets in June 2022 based on real revenue in May 2022 and passenger traffic-related features.')

st.sidebar.markdown('''Roman Permyakov ©
    <a href="https://github.com/roman-permyakov">
        <img src="https://www.seonews.ru/upload/resize_cache/iblock/a5b/120_120_1/a5bca6110d2c6c8f8e0ab44675750a7c.jpg" width="35" />
    </a>''',
    unsafe_allow_html=True
)

# New
#st.markdown('# **Passenger Traffic Maps 🌎**')
st.markdown("<h1>Passenger Traffic Maps 🌎</h1>", unsafe_allow_html=True)
st.markdown('##### **Real Data. May-June, 2022**')
#st.markdown("\n\n")

# Selectbox
option = st.selectbox('Select Type of Flights ✈️', ['Arrived', 'Departed'])
col1, col2, col3, col4, col5 = st.columns(5)
with col1:
  checkbox1 = st.checkbox('Dark Theme')
with col2:
  checkbox2 = st.checkbox('Time Lapse')

if option == "Arrived":
  if checkbox1:
    if checkbox2:
      # Карта отправлений пассажиропотока в Шереметьево
      flights_in_map = KeplerGl(height=700, data={ "all_data" : flights_in_coords }, config = map_config_in_dark)
      keplergl_static(flights_in_map)
    else:
      flights_in_map = KeplerGl(height=700, data={ "all_data" : flights_in_coords }, config = map_config_in_dark_noLegend)
      keplergl_static(flights_in_map)  
  else:
    if checkbox2:
      flights_in_map = KeplerGl(height=700, data={ "all_data" : flights_in_coords }, config = map_config_in)
      keplergl_static(flights_in_map)
    else:
      flights_in_map = KeplerGl(height=700, data={ "all_data" : flights_in_coords }, config = map_config_in_noLegend)
      keplergl_static(flights_in_map)


if option == "Departed":
  if checkbox1:
    if checkbox2:
      # Карта отправлений пассажиропотока из Шереметьево
      flights_in_map = KeplerGl(height=700, data={ "all_data" : flights_out_coords }, config = map_config_out_dark)
      keplergl_static(flights_in_map)
    else:
      flights_in_map = KeplerGl(height=700, data={ "all_data" : flights_out_coords }, config = map_config_out_dark_noLegend)
      keplergl_static(flights_in_map)  
  else:
    if checkbox2:
      flights_in_map = KeplerGl(height=700, data={ "all_data" : flights_out_coords }, config = map_config_out)
      keplergl_static(flights_in_map)
    else:
      flights_in_map = KeplerGl(height=700, data={ "all_data" : flights_out_coords }, config = map_config_out_noLegend)
      keplergl_static(flights_in_map)


